name: Bug Report
description: "Something is broken."
title: "[Bug]: "
labels: ['Potential Bug']
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a **Bug Report**, please ensure the following:

        - **1:** You are running the latest version of ComfyUI-Easy-Use-Frontend.
        - **2:** You have looked at the existing bug reports and made sure this isn't already reported.
        - **3:** You confirmed that the bug is not caused by ComfyUI main program or others custom node.
  - type: textarea
    attributes:
      label: Expected Behavior
      description: 'What you expected to happen.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: 'What actually happened. Please include a screenshot / video clip of the issue if possible.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: "Describe how to reproduce the issue. Please be sure to attach a workflow JSON or PNG, ideally one that doesn't require custom nodes to test. If the bug open happens when certain custom nodes are used, most likely that custom node is what has the bug rather than ComfyUI, in which case it should be reported to the node's author."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Debug Logs
      description: 'Please copy the output from your terminal logs here.'
      render: powershell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Browser Logs
      description: 'Please copy the output from your browser logs here. You can access this by pressing F12 to toggle the developer tools, then navigating to the Console tab.'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Other
      description: 'Any other additional information you think might be helpful.'
    validations:
      required: false